services:
  - type: web
    name: todo-backend
    env: node
    plan: free
    buildCommand: 'cd server && npm install'
    startCommand: 'node server/index.js'
    envVars:
      - key: MONGO_URI
        value: <votre_uri_mongodb>
      - key: PORT
        value: 5000

  - type: web
    name: todo-frontend
    env: node
    plan: free
    buildCommand: 'npm install && npm run build'
    startCommand: 'npm run preview'
    envVars:
      - key: VITE_API_URL
        value: <url_backend_deploye>
